local M = {}

M.commands = {
  { "File Explorer",
    { "Toggle", ":NvimTreeToggle" },
  },
  { "Config",
    { "Show keymaps", ":Telescope mapper" },
    { "Reload", ":source $MYVIMRC" },
    { "Show all extensions", ":PackerStatus" },
    { "Show colors", ":Telescope highlights" },
  },
  { "Tabs",
    { "Close", ":lua require('scripts.bufdel').delete_buffer()" },
    { "Show all", ":Telescope buffers" },
  },
  { "Find",
    { "Telescope", ":Telescope" },
    { "String", ":lua require('telescope.builtin').grep_string()" },
    { "File", ":lua require('telescope.builtin').find_files()" },
    { "Symbols", ":Telescope treesitter" },
  },
  { "Themes",
    { "Select", ":lua require('telescope.builtin').colorscheme()" },
  },
  { "Git",
    { "Preview hunk", ":Gitsigns preview_hunk" },
    { "Toggle line blame", ":Gitsigns toggle_current_line_blame" },
    { "Toggle column signs", ":Gitsigns toggle_signs" },
    { "Toggle number highlight", ":Gitsigns toggle_numhl" },
  },
  { "Notifications",
    { "History", ":Telescope notify" },
  },
  { "LSP",
    { "Show info", ":LspInfo" },
    { "Toggle list", ":TroubleToggle" },
  },
}

return M
