#!/usr/bin/env bash
# Script that installs Vim plugins

# Install vim-plug
# https://github.com/junegunn/vim-plug
curl -fLo ~/.config/vim/vimfiles/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install plugins
vim -c "PlugInstall" -c ":q!" -c ":q!"
