#!/usr/bin/env bash
# Script that installs VS Code extensions

codium --install-extension teabyii.ayu@1.0.3
codium --install-extension ms-azuretools.vscode-docker@1.20.0
codium --install-extension miguelsolorio.fluent-icons@0.0.17
codium --install-extension eamodio.gitlens@12.0.1
codium --install-extension alefragnani.project-manager@12.0.1
codium --install-extension vscodevim.vim@1.22.2
codium --install-extension ms-python.python@2022.2.1924087327
codium --install-extension EditorConfig.EditorConfig@v0.16.6
