window:
  startup_mode: Maximized
  decorations: none

live_config_reload: true

shell:
  program: /usr/bin/zsh

scrolling:
  history: 100

font:
  size: 7

  normal:
    family: RobotoMono Nerd Font Mono
    style: Light

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: false

mouse:

  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: true

# Ayu Dark Theme
colors:

  primary:
    background: '0x0A0E14'
    foreground: '0xB3B1AD'

  normal:
    black:   '0x01060E'
    red:     '0xEA6C73'
    green:   '0x91B362'
    yellow:  '0xF9AF4F'
    blue:    '0x53BDFA'
    magenta: '0xFAE994'
    cyan:    '0x90E1C6'
    white:   '0xC7C7C7'

  bright:
    black:   '0x686868'
    red:     '0xF07178'
    green:   '0xC2D94C'
    yellow:  '0xFFB454'
    blue:    '0x59C2FF'
    magenta: '0xFFEE99'
    cyan:    '0x95E6CB'
    white:   '0xFFFFFF'

custom_cursor_colors: true

cursor:
  style: Block
  unfocused_hollow: true
