window:

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  startup_mode: Maximized

  # Window decorations
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  decorations: none

# Allow change configuration without restarting
live_config_reload: true

shell:
  program: /usr/bin/zsh

font:

  # Offset is an extra space around each character. offset.y can be thought of
  # modifying the linespacing, and offset.x as modifying the letter spacing
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward
  glyph_offset:
    x: 0
    y: 0

  # Better font rendering. Works only for Mac's
  use_thin_strokes: false

mouse:

  # Threshold tells Alacritty to wait for accepting multiply clicks as double or triple click
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: true

# Ayu Dark Theme
colors:

  primary:
    background: '0x0A0E14'
    foreground: '0xB3B1AD'

  normal:
    black:   '0x01060E'
    red:     '0xEA6C73'
    green:   '0x91B362'
    yellow:  '0xF9AF4F'
    blue:    '0x53BDFA'
    magenta: '0xFAE994'
    cyan:    '0x90E1C6'
    white:   '0xC7C7C7'

  bright:
    black:   '0x686868'
    red:     '0xF07178'
    green:   '0xC2D94C'
    yellow:  '0xFFB454'
    blue:    '0x59C2FF'
    magenta: '0xFFEE99'
    cyan:    '0x95E6CB'
    white:   '0xFFFFFF'

custom_cursor_colors: true

cursor:

  # Set cursor style
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

  # When the window is not focused cursor will be rendered as hollow box
  unfocused_hollow: true
